
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.TextField;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jdesktop.layout.*;
import javax.swing.SwingWorker;
/**
 * This class a GUI, used to set the necessary options and launch the simulation
 */
public class RmasGui extends javax.swing.JFrame {
    private HashMap<String, String> algVariables = new HashMap<String, String>();
    private StartWorker sta; /*= new StartWorker();*/
    private StopWorker sto = new StopWorker();
    /**
     * Creates new form RmasGui
     */
    public RmasGui() {
        initComponents();
        variableAdder.setVisible(false);
        variableNameLabel.setVisible(false);
        variableValuesLabel.setVisible(false);
        variableValues.setVisible(false);
        variableName.setVisible(false);
        try {
            BufferedReader reader = new BufferedReader(new FileReader("gui_defaults.cfg"));
            String line;
            while ((line = reader.readLine()) != null) {
                if (line.charAt(0) != '#') {
                    String[] content = line.split(":");
                    String name = content[0];
                   
                    if (name.equals("experiment_start_time")) {
                        try {
                        start_time.setText(content[1].trim());
                        } catch (ArrayIndexOutOfBoundsException e) {
                            start_time.setText("");
                        }
                    }
                        else if (name.equals("number_of_cycles")) {
                        try {
                        num_cycle.setText(content[1].trim());
                        } catch (ArrayIndexOutOfBoundsException e) {
                            num_cycle.setText("");
                        }
                        }
                        else if (name.equals("number_of_runs")) {
                        try {
                        number_of_runs.setText(content[1].trim());
                        } catch (ArrayIndexOutOfBoundsException e) {
                            number_of_runs.setText("");
                        }
                    }
                        else if (name.equals("assignment_class")) {
                        try {
                        algorithms.setText(content[1].trim());
                        } catch (ArrayIndexOutOfBoundsException e) {
                            algorithms.setText("");
                        }
                    } else {
                        variableName.addItem(name);
                        try {
                        algVariables.put(name, content[1].trim());
                        } catch (ArrayIndexOutOfBoundsException e) {
                            
                        }
                    }
                }
                }
            reader.close();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
            System.exit(0);
        } catch (IOException e) {
            e.printStackTrace();
            System.exit(0);
        }
        try {        
            BufferedReader in = new BufferedReader(new FileReader("last_map.cfg"));
            try {
                String map = in.readLine();
                mapName.setText(map);
                fc.setSelectedFile(new File(map));
            } catch (IOException ex) {
                Logger.getLogger(RmasGui.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(RmasGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fc = new javax.swing.JFileChooser();
        algLabel = new javax.swing.JLabel();
        cycle_label = new javax.swing.JLabel();
        num_cycle = new javax.swing.JTextField();
        s_time_label = new javax.swing.JLabel();
        start_time = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        start_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        mapSelector = new javax.swing.JButton();
        mapName = new javax.swing.JTextField();
        newVariableButton = new javax.swing.JButton();
        variableAdder = new javax.swing.JButton();
        variableValues = new javax.swing.JTextField();
        variableNameLabel = new javax.swing.JLabel();
        variableValuesLabel = new javax.swing.JLabel();
        algorithms = new javax.swing.JTextField();
        number_of_runs_label = new javax.swing.JLabel();
        number_of_runs = new javax.swing.JTextField();
        variableName = new javax.swing.JComboBox();
        StopButton = new javax.swing.JButton();

        fc.setSelectedFile(new java.io.File("/home/fabio/svn_rmasbench/trunk/maps/gml/paris/map.gml"));
        fc.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                selectedFile(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        algLabel.setText("Algorithms");

        cycle_label.setText("Number of cycles:");

        num_cycle.setText("100");

        s_time_label.setText("Start times:");

        start_time.setText("30 40 50");
        start_time.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                start_timePropertyChange(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("TeX Gyre Bonum", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RMAS Benchmark");

        start_button.setText("Start Simulation!");
        start_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_buttonActionPerformed(evt);
            }
        });

        jLabel2.setText("Map:");

        mapSelector.setText("Change Map");
        mapSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mapSelectorHandler(evt);
            }
        });

        mapName.setEditable(false);
        mapName.setText(fc.getSelectedFile().getPath());

        newVariableButton.setText("Modify Variable Value");
        newVariableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newVariableButtonHandler(evt);
            }
        });

        variableAdder.setText("Modify");
        variableAdder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVariableHandler(evt);
            }
        });

        variableNameLabel.setText("Parameter Name:");

        variableValuesLabel.setText("Parameter Values:");

        algorithms.setText("DSA MaxSum");

        number_of_runs_label.setText("Number of runs:");

        number_of_runs.setText("1");

        variableName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                variableNameActionPerformed(evt);
            }
        });

        StopButton.setText("Stop");
        StopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(21, 21, 21)
                        .add(algLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 77, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(3, 3, 3)
                        .add(algorithms, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 158, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 137, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(number_of_runs_label)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(number_of_runs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(cycle_label)
                                .add(18, 18, 18)
                                .add(num_cycle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(s_time_label)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(start_time, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 101, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(jLabel2)
                                .add(18, 18, 18)
                                .add(mapName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 226, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(layout.createSequentialGroup()
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(mapSelector)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(40, 40, 40)
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 598, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(newVariableButton))
                    .add(layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(variableAdder, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 89, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                        .add(variableNameLabel)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                        .add(variableValuesLabel)
                                        .add(7, 7, 7)))
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(variableValues, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 112, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(variableName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 160, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(16, 16, 16)))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .add(261, 261, 261)
                .add(start_button, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 152, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(StopButton)
                .add(153, 153, 153))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(23, 23, 23)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(algLabel)
                            .add(algorithms, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(number_of_runs_label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(number_of_runs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(22, 22, 22)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(newVariableButton)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(cycle_label)
                        .add(num_cycle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(s_time_label)
                            .add(start_time, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel2)
                            .add(mapName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(mapSelector)
                                    .add(variableAdder))
                                .add(28, 28, 28)
                                .add(start_button, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(StopButton)))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(variableNameLabel)
                            .add(variableName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(variableValuesLabel)
                            .add(variableValues, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /* Funzione che cattura l'evento di start */
    private void start_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_buttonActionPerformed
        // TODO add your handling code here:
       // Esempio di accesso alle info
         
         String algs = algorithms.getText();
         //String num_targets = n_targets.getText();
         String n_cycle = num_cycle.getText();
         String s_time = start_time.getText();
         String n_runs = number_of_runs.getText();
         String mapDirectory = "";
         
         try {
         mapDirectory = fc.getCurrentDirectory().getCanonicalPath();
         } catch (IOException e) {}
         try {
            BufferedWriter out = new BufferedWriter(new FileWriter(new File("../boot/params.cfg")));
            out.write("assignment_group: AAMAS12\n");
            out.write("base_package: RSLBench\n");
            out.write("assignment_class: "+algs+"\n");
            for(String var: algVariables.keySet()) {
                out.write(var+": "+algVariables.get(var)+"\n");
            }
            out.write("experiment_start_time: "+s_time+"\n");
            //out.write("number_of_considered_targets: "+num_targets+"\n");
            out.write("number_of_runs: "+n_runs+"\n");
            out.write("number_of_cycles: "+n_cycle+"\n");
            out.write("map_directory: "+mapDirectory+"\n");
            out.flush();
            out.close();
         } catch (IOException e) {
             e.printStackTrace();
         }
         algVariables.clear();
         sta = new StartWorker();
         sta.execute();
         
         //richiamo del codice di avvio con dati scelti
    }//GEN-LAST:event_start_buttonActionPerformed
    
    //opens the map file chooser
    private void mapSelectorHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mapSelectorHandler
        fc.showOpenDialog(this);
    }//GEN-LAST:event_mapSelectorHandler

    private void selectedFile(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_selectedFile
        if (fc.SELECTED_FILE_CHANGED_PROPERTY.equals(evt.getPropertyName())) {
            try {
                mapName.setText(fc.getSelectedFile().getPath());
                try {
                    BufferedWriter out = new BufferedWriter(new FileWriter(new File("last_map.cfg")));
                    out.write(fc.getSelectedFile().getPath());
                    out.flush();
                    out.close();
                } catch (IOException ex) {
                    Logger.getLogger(RmasGui.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (NullPointerException e) {}
        }   
    }//GEN-LAST:event_selectedFile

    private void newVariableButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newVariableButtonHandler
        newVariableButton.setVisible(false);
        variableAdder.setVisible(true);
        variableNameLabel.setVisible(true);
        variableValuesLabel.setVisible(true);
        variableValues.setVisible(true);
        variableName.setVisible(true);
        
    }//GEN-LAST:event_newVariableButtonHandler

    private void addVariableHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVariableHandler
        newVariableButton.setVisible(true);
        variableAdder.setVisible(false);
        variableNameLabel.setVisible(false);
        variableValuesLabel.setVisible(false);
        variableValues.setVisible(false);
        variableName.setVisible(false);
        if (!variableValues.getText().equals("")) {
            algVariables.put((String)variableName.getSelectedItem(), variableValues.getText());
        }
        
    }//GEN-LAST:event_addVariableHandler

    private void variableNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_variableNameActionPerformed
        // TODO add your handling code here:
        try {
            BufferedReader reader = new BufferedReader(new FileReader("gui_defaults.cfg"));
            String line;
            while ((line = reader.readLine()) != null) {
                 String[] content = line.split(":");
                    String name = content[0];
                    if (name.equals(variableName.getSelectedItem())) {
                    String values;
                    try {
                    values = content[1].trim();
                    } catch (ArrayIndexOutOfBoundsException e) {
                        values = "";
                    }
                        variableValues.setText(values);
                    
            }
            }
       } catch (FileNotFoundException e) {
            e.printStackTrace();
            System.exit(0);
        } catch (IOException e) {
            e.printStackTrace();
            System.exit(0);
        }
    }//GEN-LAST:event_variableNameActionPerformed

    private void StopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopButtonActionPerformed
        // TODO add your handling code here:
        //sto.cancel(true);
        sta.cancel(true);
        sto = new StopWorker();
        sto.execute();
    }//GEN-LAST:event_StopButtonActionPerformed

    private void start_timePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_start_timePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_start_timePropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RmasGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RmasGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RmasGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RmasGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RmasGui().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton StopButton;
    private javax.swing.JLabel algLabel;
    private javax.swing.JTextField algorithms;
    private javax.swing.JLabel cycle_label;
    private javax.swing.JFileChooser fc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField mapName;
    private javax.swing.JButton mapSelector;
    private javax.swing.JButton newVariableButton;
    private javax.swing.JTextField num_cycle;
    private javax.swing.JTextField number_of_runs;
    private javax.swing.JLabel number_of_runs_label;
    private javax.swing.JLabel s_time_label;
    private javax.swing.JButton start_button;
    private javax.swing.JTextField start_time;
    private javax.swing.JButton variableAdder;
    private javax.swing.JComboBox variableName;
    private javax.swing.JLabel variableNameLabel;
    private javax.swing.JTextField variableValues;
    private javax.swing.JLabel variableValuesLabel;
    // End of variables declaration//GEN-END:variables
}
